### ISSUE TITLE
Message count not shown anymore after upgrading thunderbird to 24.0.1

### ISSUE THREAD

**Issue by robyf** [foudfou/FireTray#100]
After upgrading thunderbird to 24.0.1 the message count is not displayed in the tray anymore (on debian wheeze). In the error console there's this:

Date and time: 12/10/2013 20:42:53
Error: ERROR firetray: TypeError: accounts.Count is not a function
Source file: resource://firetray/FiretrayMessaging.jsm
Row: 118
